import type { CosmeticDef, EquipmentDef, ModuleDef } from './types.js';

/**
 * Ship modules. Modules are the only things that change ship stats besides
 * upgrade tiers, and every one of them is craftable — nothing here is
 * purchasable with real money, and nothing that is on-chain grants raw power
 * beyond what a crafted equivalent gives (see ECONOMY.md, "no pay-to-win").
 */
export const MODULES: readonly ModuleDef[] = [
  {
    id: 'mining_laser_i',
    name: 'Mining Laser I',
    description: 'Entry-level extraction beam. Doubles what a bare hull can pull from an asteroid.',
    slot: 'mining',
    rarity: 'common',
    stats: { miningPower: 8 },
    craftableWith: 'recipe_mining_laser_i',
    creditPrice: 1200,
    onChainEligible: false,
  },
  {
    id: 'mining_laser_ii',
    name: 'Advanced Mining Laser',
    description:
      'Resonance-tuned emitter. Cuts platinum and crystal that a stock beam cannot even scratch.',
    slot: 'mining',
    rarity: 'rare',
    stats: { miningPower: 22 },
    multipliers: { miningPower: 1.1 },
    craftableWith: 'recipe_mining_laser_ii',
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'harmonic_extractor',
    name: 'Harmonic Extractor',
    description: 'Phase-locked drill head. The only civilian rig rated for Quantum Shard recovery.',
    slot: 'mining',
    rarity: 'legendary',
    stats: { miningPower: 44, sensors: 10 },
    multipliers: { miningPower: 1.2 },
    craftableWith: 'recipe_harmonic_extractor',
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'cargo_expander',
    name: 'Cargo Expander',
    description: 'Folded-space bracing in the hold. More room, no extra hull.',
    slot: 'cargo',
    rarity: 'uncommon',
    stats: { cargo: 80 },
    craftableWith: 'recipe_cargo_expander',
    creditPrice: 3400,
    onChainEligible: false,
  },
  {
    id: 'cargo_singularity',
    name: 'Singularity Hold',
    description: 'A very small, very well-behaved gravity well where the cargo bay used to be.',
    slot: 'cargo',
    rarity: 'epic',
    stats: { cargo: 240 },
    multipliers: { cargo: 1.15 },
    craftableWith: 'recipe_cargo_singularity',
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'ion_thruster',
    name: 'Ion Thruster',
    description: 'Quiet, efficient, and slightly faster than the manufacturer will admit in writing.',
    slot: 'engine',
    rarity: 'uncommon',
    stats: { speed: 9 },
    craftableWith: 'recipe_ion_thruster',
    creditPrice: 2900,
    onChainEligible: false,
  },
  {
    id: 'fusion_drive',
    name: 'Fusion Drive',
    description: 'Helium-3 burner. Halves travel time to the outer belts and drinks accordingly.',
    slot: 'engine',
    rarity: 'epic',
    stats: { speed: 24, fuel: 60 },
    craftableWith: 'recipe_fusion_drive',
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'deflector_i',
    name: 'Deflector Array',
    description: 'Standard hazard shielding. Turns a bad day in the belt into an expensive one.',
    slot: 'shield',
    rarity: 'common',
    stats: { defense: 14 },
    craftableWith: 'recipe_deflector_i',
    creditPrice: 1600,
    onChainEligible: false,
  },
  {
    id: 'aegis_shield',
    name: 'Aegis Barrier',
    description: 'Federation-grade layered shielding. Rated for Syndicate space, unofficially.',
    slot: 'shield',
    rarity: 'rare',
    stats: { defense: 42 },
    craftableWith: 'recipe_aegis_shield',
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'survey_scanner',
    name: 'Survey Scanner',
    description: 'Wide-band sensor package. Finds the veins other rigs fly straight past.',
    slot: 'utility',
    rarity: 'uncommon',
    stats: { sensors: 26 },
    craftableWith: 'recipe_survey_scanner',
    creditPrice: 3100,
    onChainEligible: false,
  },
  {
    id: 'deep_scanner',
    name: 'Deep-Field Scanner',
    description: 'Quantum-coupled array. Raises the odds on every rare roll you make in the field.',
    slot: 'utility',
    rarity: 'epic',
    stats: { sensors: 64 },
    craftableWith: 'recipe_deep_scanner',
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'pulse_cannon',
    name: 'Pulse Cannon',
    description: 'Point-defence turret. Discourages the sort of company you meet past the Rift.',
    slot: 'weapon',
    rarity: 'rare',
    stats: { defense: 26, speed: -2 },
    craftableWith: 'recipe_pulse_cannon',
    creditPrice: 8800,
    onChainEligible: false,
  },
];

export const MODULES_BY_ID: ReadonlyMap<string, ModuleDef> = new Map(MODULES.map((m) => [m.id, m]));

/**
 * Personal equipment. These stats affect *station* play (walk speed, energy,
 * refining yield) and deliberately never touch ship combat power.
 */
export const EQUIPMENT: readonly EquipmentDef[] = [
  {
    id: 'suit_standard',
    name: 'Station Issue Suit',
    description: 'Nova Station general issue. Warm, airtight, unfashionable.',
    slot: 'suit',
    rarity: 'common',
    stats: { energyMax: 100 },
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'suit_surveyor',
    name: 'Surveyor Rig',
    description: 'Federation field suit with a powered exo-frame. You will notice the stairs less.',
    slot: 'suit',
    rarity: 'uncommon',
    stats: { walkSpeed: 0.6, energyMax: 130, energyRegen: 1.5 },
    creditPrice: 5200,
    onChainEligible: false,
  },
  {
    id: 'suit_voidwalker',
    name: 'Voidwalker Shell',
    description: 'Syndicate pressure shell. Nobody asks where the plating came from.',
    slot: 'suit',
    rarity: 'epic',
    stats: { walkSpeed: 1.2, energyMax: 180, energyRegen: 3 },
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'helmet_standard',
    name: 'Standard Helm',
    description: 'Polycarbonate bubble, single visor lamp, works.',
    slot: 'helmet',
    rarity: 'common',
    stats: {},
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'helmet_prospector',
    name: 'Prospector Visor',
    description: 'Overlays ore density straight onto the glass. Miners swear by it.',
    slot: 'helmet',
    rarity: 'rare',
    stats: { scanRange: 12 },
    creditPrice: 7400,
    onChainEligible: false,
  },
  {
    id: 'tool_cutter',
    name: 'Hand Cutter',
    description: 'Short-range plasma cutter for station salvage and stubborn crates.',
    slot: 'tool',
    rarity: 'common',
    stats: {},
    creditPrice: 400,
    onChainEligible: false,
  },
  {
    id: 'tool_refiner',
    name: 'Portable Refiner',
    description: 'Field assay unit. Squeezes a few more percent out of every batch you process.',
    slot: 'tool',
    rarity: 'rare',
    stats: { refineYield: 0.08 },
    creditPrice: 9600,
    onChainEligible: true,
  },
  {
    id: 'badge_recruit',
    name: 'Recruit Badge',
    description: 'Proof you made it through the airlock.',
    slot: 'badge',
    rarity: 'common',
    stats: {},
    creditPrice: 0,
    onChainEligible: false,
  },
];

export const EQUIPMENT_BY_ID: ReadonlyMap<string, EquipmentDef> = new Map(
  EQUIPMENT.map((e) => [e.id, e]),
);

/** Cosmetics never carry stats. Basic ones are free; a few rare ones are on-chain. */
export const COSMETICS: readonly CosmeticDef[] = [
  {
    id: 'pattern_plain',
    name: 'Plain',
    slot: 'suitPattern',
    rarity: 'common',
    render: { pattern: 'plain' },
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'pattern_stripe',
    name: 'Service Stripe',
    slot: 'suitPattern',
    rarity: 'common',
    render: { pattern: 'stripe' },
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'pattern_hex',
    name: 'Hex Weave',
    slot: 'suitPattern',
    rarity: 'uncommon',
    render: { pattern: 'hex' },
    creditPrice: 1800,
    onChainEligible: false,
  },
  {
    id: 'pattern_circuit',
    name: 'Circuit Bloom',
    slot: 'suitPattern',
    rarity: 'epic',
    render: { pattern: 'circuit' },
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'visor_amber',
    name: 'Amber Visor',
    slot: 'visor',
    rarity: 'common',
    render: { color: '#fbbf24' },
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'visor_ice',
    name: 'Ice Visor',
    slot: 'visor',
    rarity: 'common',
    render: { color: '#7dd3fc' },
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'visor_void',
    name: 'Void Visor',
    slot: 'visor',
    rarity: 'rare',
    render: { color: '#f43f5e' },
    creditPrice: 2600,
    onChainEligible: false,
  },
  {
    id: 'emblem_federation',
    name: 'Federation Sigil',
    slot: 'emblem',
    rarity: 'uncommon',
    render: { shape: 'chevron', color: '#60a5fa' },
    creditPrice: 900,
    onChainEligible: false,
  },
  {
    id: 'emblem_helix',
    name: 'Helix Mark',
    slot: 'emblem',
    rarity: 'uncommon',
    render: { shape: 'helix', color: '#fbbf24' },
    creditPrice: 900,
    onChainEligible: false,
  },
  {
    id: 'emblem_void',
    name: 'Syndicate Brand',
    slot: 'emblem',
    rarity: 'uncommon',
    render: { shape: 'slash', color: '#f43f5e' },
    creditPrice: 900,
    onChainEligible: false,
  },
  {
    id: 'trail_ion',
    name: 'Ion Trail',
    slot: 'trail',
    rarity: 'rare',
    render: { color: '#38bdf8', particles: 24 },
    creditPrice: 4200,
    onChainEligible: false,
  },
  {
    id: 'trail_nova',
    name: 'Nova Trail',
    slot: 'trail',
    rarity: 'legendary',
    render: { color: '#c084fc', particles: 48 },
    creditPrice: null,
    onChainEligible: true,
  },
  {
    id: 'accessory_none',
    name: 'None',
    slot: 'accessory',
    rarity: 'common',
    render: { shape: 'none' },
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'accessory_pack',
    name: 'Field Pack',
    slot: 'accessory',
    rarity: 'common',
    render: { shape: 'pack' },
    creditPrice: 0,
    onChainEligible: false,
  },
  {
    id: 'accessory_antenna',
    name: 'Survey Antenna',
    slot: 'accessory',
    rarity: 'uncommon',
    render: { shape: 'antenna' },
    creditPrice: 1400,
    onChainEligible: false,
  },
  {
    id: 'accessory_wings',
    name: 'Manoeuvre Vanes',
    slot: 'accessory',
    rarity: 'epic',
    render: { shape: 'vanes' },
    creditPrice: null,
    onChainEligible: true,
  },
];

export const COSMETICS_BY_ID: ReadonlyMap<string, CosmeticDef> = new Map(
  COSMETICS.map((c) => [c.id, c]),
);

/** Cosmetics available to every player from the first second, with no cost. */
export const DEFAULT_COSMETIC_IDS: readonly string[] = COSMETICS.filter(
  (c) => c.creditPrice === 0,
).map((c) => c.id);

export const DEFAULT_EQUIPMENT_IDS: readonly string[] = EQUIPMENT.filter(
  (e) => e.creditPrice === 0,
).map((e) => e.id);
