import type { MissionDef, MissionType } from './types.js';

/**
 * Mission catalogue.
 *
 * Missions are pure data: the UI renders whatever is in this table and the
 * server resolves objectives against player events. Adding a mission never
 * requires touching a React component.
 */
export const MISSIONS: readonly MissionDef[] = [
  {
    id: 'first_haul',
    code: 1,
    title: 'First Haul',
    summary: 'Bring back anything at all from the Nova Belt.',
    briefing:
      'Dock control has your flight plan. Take the Kestrel out to the Nova Belt, fill whatever hold you have, and come home in one piece. Nobody expects a fortune on your first run.',
    type: 'mining',
    difficulty: 1,
    faction: 'helix',
    requiredLevel: 1,
    requiredFactionRank: 0,
    requiredShipClasses: [],
    objectives: [{ kind: 'mine_any', amount: 40 }],
    durationSec: 60 * 45,
    reward: {
      xp: 120,
      credits: 400,
      reputation: { faction: 'helix', amount: 60 },
      resources: [{ resource: 'iron', amount: 10 }],
    },
    risk: 0.05,
    repeatable: false,
    cooldownSec: 0,
  },
  {
    id: 'station_orientation',
    code: 2,
    title: 'Station Orientation',
    summary: 'Report to the Command Deck for your registry check.',
    briefing:
      'Every hull that docks here gets logged. Walk up to the Command Deck, let the registry read your suit tag, and you are officially a resident rather than a visitor.',
    type: 'exploration',
    difficulty: 1,
    faction: 'federation',
    requiredLevel: 1,
    requiredFactionRank: 0,
    requiredShipClasses: [],
    objectives: [{ kind: 'visit', area: 'command_deck' }],
    durationSec: 60 * 30,
    reward: { xp: 80, credits: 250, reputation: { faction: 'federation', amount: 80 } },
    risk: 0,
    repeatable: false,
    cooldownSec: 0,
  },
  {
    id: 'iron_quota',
    code: 7,
    title: 'Iron Quota',
    summary: 'Deliver 120 Iron to the Helix collection point.',
    briefing:
      'Helix runs the station’s structural repair budget and it is running short. Standard rate, paid on delivery, no bonuses for enthusiasm.',
    type: 'delivery',
    difficulty: 1,
    faction: 'helix',
    requiredLevel: 2,
    requiredFactionRank: 0,
    requiredShipClasses: [],
    objectives: [{ kind: 'deliver', resource: 'iron', amount: 120 }],
    durationSec: 60 * 60,
    reward: { xp: 180, credits: 900, reputation: { faction: 'helix', amount: 110 } },
    risk: 0.05,
    repeatable: true,
    cooldownSec: 60 * 30,
  },
  {
    id: 'lost_mining_drone',
    code: 42,
    title: 'Lost Mining Drone',
    summary: 'Recover a survey drone that stopped reporting in Kestrel Reach.',
    briefing:
      'A Helix drone went quiet mid-sweep three days ago. Its last telemetry puts it somewhere in Kestrel Reach. Sweep the field, find what is left of it, and bring the core home. The salvage is yours.',
    type: 'recovery',
    difficulty: 3,
    faction: 'helix',
    requiredLevel: 4,
    requiredFactionRank: 1,
    requiredShipClasses: [],
    objectives: [
      { kind: 'expedition', zone: 'kestrel_reach', amount: 1 },
      { kind: 'mine_any', amount: 150 },
    ],
    durationSec: 60 * 8,
    reward: {
      xp: 150,
      credits: 1800,
      reputation: { faction: 'helix', amount: 50 },
      resources: [{ resource: 'titanium', amount: 25 }],
      rareChance: 0.18,
      rareDrop: { kind: 'module', id: 'survey_scanner' },
    },
    risk: 0.2,
    repeatable: true,
    cooldownSec: 60 * 45,
  },
  {
    id: 'crystal_survey',
    code: 55,
    title: 'Resonance Survey',
    summary: 'Scan 6 crystal-bearing rocks for the Laboratory.',
    briefing:
      'The Lab wants clean resonance profiles, not ore. Fly out, hold a beam on six crystal-bearing rocks long enough to log the harmonics, and try not to shatter them in the process.',
    type: 'research',
    difficulty: 2,
    faction: 'federation',
    requiredLevel: 5,
    requiredFactionRank: 1,
    requiredShipClasses: [],
    objectives: [{ kind: 'scan', zone: 'kestrel_reach', amount: 6 }],
    durationSec: 60 * 40,
    reward: {
      xp: 260,
      credits: 1500,
      reputation: { faction: 'federation', amount: 160 },
      resources: [{ resource: 'crystal', amount: 8 }],
    },
    risk: 0.12,
    repeatable: true,
    cooldownSec: 60 * 60,
  },
  {
    id: 'refinery_backlog',
    code: 61,
    title: 'Refinery Backlog',
    summary: 'Process 300 units of raw ore through the Mining Bay refinery.',
    briefing:
      'The refinery queue is three shifts deep and the foreman is offering a cut to anyone who clears some of it. Bring your own ore.',
    type: 'trade',
    difficulty: 2,
    faction: 'helix',
    requiredLevel: 5,
    requiredFactionRank: 1,
    requiredShipClasses: [],
    objectives: [{ kind: 'refine', amount: 300 }],
    durationSec: 60 * 90,
    reward: { xp: 300, credits: 2200, reputation: { faction: 'helix', amount: 180 } },
    risk: 0,
    repeatable: true,
    cooldownSec: 60 * 60,
  },
  {
    id: 'blackline_run',
    code: 73,
    title: 'Blackline Run',
    summary: 'Move 60 Platinum without filing a manifest.',
    briefing:
      'A booth in the Market has sixty units of platinum it would rather not discuss with the Federation. Take it off their hands. You will not find this on any terminal but this one.',
    type: 'trade',
    difficulty: 3,
    faction: 'void',
    requiredLevel: 7,
    requiredFactionRank: 1,
    requiredShipClasses: [],
    objectives: [{ kind: 'deliver', resource: 'platinum', amount: 60 }],
    durationSec: 60 * 70,
    reward: {
      xp: 420,
      credits: 5200,
      reputation: { faction: 'void', amount: 260 },
      rareChance: 0.12,
      rareDrop: { kind: 'cosmetic', id: 'visor_void' },
    },
    risk: 0.3,
    repeatable: true,
    cooldownSec: 60 * 75,
  },
  {
    id: 'stranded_prospector',
    code: 88,
    title: 'Stranded Prospector',
    summary: 'Reach a stranded prospector in Helix Claim 44 before their air runs out.',
    briefing:
      'A freelancer burnt their last fuel chasing a vein and is drifting inside the claim. Helix will not send a rig. Get there, get them aboard, get out. The clock is not generous.',
    type: 'rescue',
    difficulty: 4,
    faction: 'federation',
    requiredLevel: 9,
    requiredFactionRank: 2,
    requiredShipClasses: ['scout', 'explorer', 'transport'],
    objectives: [{ kind: 'expedition', zone: 'helix_claim', amount: 1 }],
    durationSec: 60 * 12,
    reward: {
      xp: 620,
      credits: 6800,
      reputation: { faction: 'federation', amount: 340 },
      rareChance: 0.22,
      rareDrop: { kind: 'equipment', id: 'helmet_prospector' },
    },
    risk: 0.35,
    repeatable: true,
    cooldownSec: 60 * 120,
  },
  {
    id: 'escort_duty',
    code: 91,
    title: 'Escort Duty',
    summary: 'Run a defended sweep through Helix Claim 44.',
    briefing:
      'Two rigs went dark on the claim edge last cycle. Helix wants an armed hull in the field while the replacement drones deploy. Bring shielding; bring a cannon if you have one.',
    type: 'combat',
    difficulty: 4,
    faction: 'helix',
    requiredLevel: 11,
    requiredFactionRank: 3,
    requiredShipClasses: ['combat', 'explorer'],
    objectives: [
      { kind: 'expedition', zone: 'helix_claim', amount: 2 },
      { kind: 'mine_any', amount: 200 },
    ],
    durationSec: 60 * 25,
    reward: {
      xp: 780,
      credits: 9400,
      reputation: { faction: 'helix', amount: 420 },
      resources: [{ resource: 'platinum', amount: 20 }],
      rareChance: 0.2,
      rareDrop: { kind: 'module', id: 'pulse_cannon' },
    },
    risk: 0.45,
    repeatable: true,
    cooldownSec: 60 * 150,
  },
  {
    id: 'lab_commission',
    code: 104,
    title: 'Laboratory Commission',
    summary: 'Craft a Survey Scanner for the Lab.',
    briefing:
      'The Lab has parts on order and no bench time. Build them a scanner to spec and they will pay above catalogue for the favour.',
    type: 'research',
    difficulty: 2,
    faction: 'federation',
    requiredLevel: 6,
    requiredFactionRank: 1,
    requiredShipClasses: [],
    objectives: [{ kind: 'craft', recipe: 'recipe_survey_scanner', amount: 1 }],
    durationSec: 60 * 120,
    reward: { xp: 340, credits: 2600, reputation: { faction: 'federation', amount: 200 } },
    risk: 0,
    repeatable: true,
    cooldownSec: 60 * 90,
  },
  {
    id: 'deep_field_charting',
    code: 117,
    title: 'Deep-Field Charting',
    summary: 'Log 12 scans across The Rift.',
    briefing:
      'Nobody has produced a usable chart of the Rift in nine years. Twelve clean scans and the Federation will call it a survey. Everything past the fourth is your own risk.',
    type: 'exploration',
    difficulty: 5,
    faction: 'federation',
    requiredLevel: 15,
    requiredFactionRank: 4,
    requiredShipClasses: ['explorer', 'scout'],
    objectives: [{ kind: 'scan', zone: 'the_rift', amount: 12 }],
    durationSec: 60 * 45,
    reward: {
      xp: 1500,
      credits: 18000,
      reputation: { faction: 'federation', amount: 700 },
      resources: [{ resource: 'quantum_shard', amount: 2 }],
      rareChance: 0.3,
      rareDrop: { kind: 'module', id: 'deep_scanner' },
    },
    risk: 0.55,
    repeatable: true,
    cooldownSec: 60 * 180,
  },
  {
    id: 'shard_contract',
    code: 128,
    title: 'Shard Contract',
    summary: 'Deliver 6 Quantum Shards to the Syndicate booth.',
    briefing:
      'Six shards. No questions, no registry entry, no receipt. The booth pays in credits and in the sort of standing that opens doors on the lower deck.',
    type: 'delivery',
    difficulty: 5,
    faction: 'void',
    requiredLevel: 16,
    requiredFactionRank: 4,
    requiredShipClasses: [],
    objectives: [{ kind: 'deliver', resource: 'quantum_shard', amount: 6 }],
    durationSec: 60 * 120,
    reward: {
      xp: 1800,
      credits: 26000,
      reputation: { faction: 'void', amount: 900 },
      rareChance: 0.25,
      rareDrop: { kind: 'cosmetic', id: 'trail_nova' },
    },
    risk: 0.5,
    repeatable: true,
    cooldownSec: 60 * 240,
  },
  {
    id: 'market_maker',
    code: 133,
    title: 'Market Maker',
    summary: 'Complete 5 marketplace sales.',
    briefing:
      'The Market wants liquidity, not hoarders. Move five lots through the exchange and the guild will note the service.',
    type: 'trade',
    difficulty: 2,
    faction: 'helix',
    requiredLevel: 6,
    requiredFactionRank: 1,
    requiredShipClasses: [],
    objectives: [{ kind: 'sell', amount: 5 }],
    durationSec: 60 * 240,
    reward: { xp: 400, credits: 3000, reputation: { faction: 'helix', amount: 240 } },
    risk: 0,
    repeatable: true,
    cooldownSec: 60 * 180,
  },
  {
    id: 'helium_run',
    code: 140,
    title: 'Helium Run',
    summary: 'Extract 80 Helium-3 from any field.',
    briefing:
      'Station reactors run on He-3 and the strategic reserve is thin. Any field, any method, as long as it is eighty units and it is this cycle.',
    type: 'mining',
    difficulty: 4,
    faction: 'federation',
    requiredLevel: 12,
    requiredFactionRank: 3,
    requiredShipClasses: [],
    objectives: [{ kind: 'mine', resource: 'helium3', amount: 80 }],
    durationSec: 60 * 90,
    reward: {
      xp: 900,
      credits: 11000,
      reputation: { faction: 'federation', amount: 460 },
      resources: [{ resource: 'helium3', amount: 10 }],
    },
    risk: 0.28,
    repeatable: true,
    cooldownSec: 60 * 120,
  },
  {
    id: 'hangar_inspection',
    code: 145,
    title: 'Hangar Inspection',
    summary: 'Present a ship at the Hangar for certification.',
    briefing:
      'Station safety wants eyes on every hull that flies from bay two. Bring a ship to the Hangar console and let them sign it off.',
    type: 'exploration',
    difficulty: 1,
    faction: 'federation',
    requiredLevel: 2,
    requiredFactionRank: 0,
    requiredShipClasses: [],
    objectives: [{ kind: 'visit', area: 'hangar' }],
    durationSec: 60 * 30,
    reward: { xp: 100, credits: 350, reputation: { faction: 'federation', amount: 70 } },
    risk: 0,
    repeatable: false,
    cooldownSec: 0,
  },
  {
    id: 'titanium_contract',
    code: 152,
    title: 'Titanium Contract',
    summary: 'Deliver 200 Titanium to Helix.',
    briefing:
      'Frame stock for the next hull batch. Two hundred units, standard purity, delivered to the Mining Bay dock.',
    type: 'delivery',
    difficulty: 3,
    faction: 'helix',
    requiredLevel: 8,
    requiredFactionRank: 2,
    requiredShipClasses: [],
    objectives: [{ kind: 'deliver', resource: 'titanium', amount: 200 }],
    durationSec: 60 * 90,
    reward: {
      xp: 520,
      credits: 4800,
      reputation: { faction: 'helix', amount: 300 },
      rareChance: 0.1,
      rareDrop: { kind: 'module', id: 'cargo_expander' },
    },
    risk: 0.1,
    repeatable: true,
    cooldownSec: 60 * 90,
  },
  {
    id: 'derelict_sweep',
    code: 166,
    title: 'Derelict Sweep',
    summary: 'Recover salvage from the Rift wreck line.',
    briefing:
      'There is a line of hulls out past the Rift boundary that nobody has claimed because nobody has come back. The Syndicate is willing to fund one more attempt.',
    type: 'recovery',
    difficulty: 5,
    faction: 'void',
    requiredLevel: 17,
    requiredFactionRank: 5,
    requiredShipClasses: ['combat', 'explorer'],
    objectives: [
      { kind: 'expedition', zone: 'the_rift', amount: 3 },
      { kind: 'mine_any', amount: 400 },
    ],
    durationSec: 60 * 60,
    reward: {
      xp: 2400,
      credits: 34000,
      reputation: { faction: 'void', amount: 1200 },
      resources: [{ resource: 'quantum_shard', amount: 4 }],
      rareChance: 0.35,
      rareDrop: { kind: 'equipment', id: 'suit_voidwalker' },
    },
    risk: 0.7,
    repeatable: true,
    cooldownSec: 60 * 300,
  },
  {
    id: 'lab_synthesis',
    code: 171,
    title: 'Lab Synthesis',
    summary: 'Craft an Advanced Mining Laser under Federation supervision.',
    briefing:
      'The Lab will lend you a bench and a supervisor. Produce one resonance-tuned laser to their tolerances and the schematic rights stay with you.',
    type: 'research',
    difficulty: 4,
    faction: 'federation',
    requiredLevel: 10,
    requiredFactionRank: 3,
    requiredShipClasses: [],
    objectives: [{ kind: 'craft', recipe: 'recipe_mining_laser_ii', amount: 1 }],
    durationSec: 60 * 180,
    reward: {
      xp: 950,
      credits: 7600,
      reputation: { faction: 'federation', amount: 500 },
      resources: [{ resource: 'crystal', amount: 12 }],
    },
    risk: 0,
    repeatable: true,
    cooldownSec: 60 * 240,
  },
];

export const MISSIONS_BY_ID: ReadonlyMap<string, MissionDef> = new Map(
  MISSIONS.map((m) => [m.id, m]),
);

export const MISSION_TYPE_LABEL: Readonly<Record<MissionType, string>> = {
  mining: 'Mining',
  exploration: 'Exploration',
  delivery: 'Delivery',
  recovery: 'Recovery',
  rescue: 'Rescue',
  combat: 'Combat',
  research: 'Research',
  trade: 'Trade',
};

export const MISSION_TYPE_ICON: Readonly<Record<MissionType, string>> = {
  mining: '⛏',
  exploration: '✦',
  delivery: '⇄',
  recovery: '⟲',
  rescue: '✚',
  combat: '⚔',
  research: '⚗',
  trade: '⇅',
};

/** Maximum missions a player may hold at once. */
export const MAX_ACTIVE_MISSIONS = 4;
